const itemData = [
  { id: '1', name: '输入框', type: 'input', uuid: 1, componentType: 'simple' },
  { id: '15', name: '文本框', type: 'textarea', uuid: 15, componentType: 'simple' },
  { id: '2', name: '下拉框', type: 'select', uuid: 2, componentType: 'simple' },
  { id: '3', name: '数字输入框', type: 'number', uuid: 3, componentType: 'simple' },
  {
    id: '6',
    name: '上传文件',
    type: 'upload',
    uuid: 6,
    componentType: 'simple',
    uploadText: '点击上传文件',
  },
  {
    id: '16',
    name: '上传图片',
    type: 'uploadPic',
    accept: 'image/*',
    listType: 'picture-card',
    uuid: 16,
    componentType: 'simple',
    uploadText: '点击上传图片',
  },
  // { id: '9', name: '级联组件', type: 'cascader', uuid: 9, componentType: 'simple' },
  { id: '10', name: '树形选择', type: 'treeSelect', uuid: 10, componentType: 'simple' },
  // { id: '11', name: '多选', type: 'checkbox', uuid: 11, componentType: 'simple' },
  // { id: '12', name: '单选', type: 'radio', uuid: 12, componentType: 'simple' },
  { id: '13', name: '日期选择器(点)', type: 'datepicker', uuid: 13, componentType: 'simple' },
  { id: '14', name: '日期选择器(时间段)', type: 'rangepicker', uuid: 14, componentType: 'simple' },
  { id: '17', name: '明细', type: 'detailList', uuid: 14, componentType: 'simple' },
  { id: '7', name: '请假组件', type: 'leave', uuid: 7, componentType: 'own', leaveLayout: 'vertical' },
  // {
  //   id: '8',
  //   name: '出差组件',
  //   type: 'out',
  //   uuid: 8,
  //   componentType: 'own',
  //   isPingjie: true,
  //   leaveLayout: 'vertical',
  //   children: [
  //     { id: '9', name: '备注', type: 'input', uuid: 'out-remark', componentType: 'simple', colSpan: 24 },
  //     {
  //       id: '10',
  //       name: '原因',
  //       type: 'select',
  //       selectType: 1,
  //       uuid: 'out-reason',
  //       componentType: 'simple',
  //       colSpan: 24,
  //       options: [{ id: 1, label: 'text1', value: '1' }],
  //     },
  //   ],
  // },
];

export { itemData };
